{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roboshop-{{ .Values.appName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/hostname: frontend-dev.sdevops.shop
spec:
  ingressClassName : nginx
  rules:
    - host: "frontend-dev.sdevops.shop"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
               name: roboshop-{{ .Values.appName }}
               port:
                  number: {{.Values.service.port}}
{{- end }}